name: CI

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  src-test:
    name: torch.stft consistency
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python dependencies
      run: |
        uv pip install -r requirements.txt
        python --version
        uv --version
        uv tree
      shell: bash

    - name: Test against torch.stft
      run: |
        coverage run --append --module pytest \
          tests/torch_stft_test.py

    - name: Coverage report
      run: |
        coverage report --show-missing
        coverage xml -o coverage.xml

    - name: Codecov upload
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
