name: Linter
on: [push, pull_request]

jobs:
  code-black:
    name: Linting & Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install a specific version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
          enable-cache: false

      - name: Install ruff
        # Keep version in sync with pre-commit and requirements.txt
        run: pip install ruff==0.9.1

      - name: Run ruff format
        run: |
          ruff format --diff \
            asteroid_filterbanks \
            tests

      - name: Run ruff check
        # Exit on important linting errors and warn about others.
        run: |
          ruff check --diff --select=F6,F7,F82,F52 \
            asteroid_filterbanks \
            tests
          ruff check --statistics --exit-zero \
            asteroid_filterbanks \
            tests
